### ISSUE TITLE
Add django 4.1+ compatibility.

### ISSUE THREAD

**Issue by fabiocaccamo** [KUWAITNET/django-admin-commands#1]
```ImportError: cannot import name 'force_text' from 'django.utils.encoding'```

**Comment by RamezIssac** [comment]
Noted

**Comment by RamezIssac** [comment]
Done 
https://pypi.org/project/django-admin-commands2/1.1.2/

Thanks !

**Comment by fabiocaccamo** [comment]
Thank you!
